export const ADD_SELECTION = "ADD_SELECTION";
export const GET_SELECTIONS = "GET_SELECTION";
export const EDIT_SELECTION = "EDIT_SELECTION";
export const DELETE_SELECTION = "DELETE_SELECTION";
export const DELETE_SELECTIONS = "DELETE_SELECTIONS";
export const SET_SELECTION_ID = "SET_SELECTION_ID";