export const ADD_SELECTION = "ADD_SELECTION";
export const GET_SELECTIONS = "GET_SELECTION";
export const EDIT_SELECTION = "EDIT_SELECTION";
export const DELETE_SELECTION = "DELETE_SELECTION";
export const DELETE_SELECTIONS = "DELETE_SELECTIONS";
export const SET_SELECTION_ID = "SET_SELECTION_ID";

export const ADD_TO_CHART = "ADD_TO_CHART";
export const GET_CHART = "GET_CHART";
export const REMOVE_FROM_CHART = "REMOVE_FROM_CHART";
export const CLEAR_CHART = "CLEAR_CHART";