export const dummySelections = [
  // first 10 should be "Acceptable"
  // next 10 are high rated, but only 3 being S Plus (over 15 likes)
  // next 5 are low rated
  // next 5 are LOWWWWW rated
  // next 3 have no votes
  {
    id: 1,
    description: "Some descriptor text",
    img: "",
    name: "test1",
    netLikes: 0,
    thumbsUpVoters: ["1", "2", "3", "4", "5"],
    thumbsDownVoters: ["1", "2", "3", "4", "5"],
    userId: "123",
  },
  {
    id: 2,
    description: "Some descriptor text",
    img: "",
    name: "test2",
    netLikes: 5,
    thumbsUpVoters: ["1", "2", "3", "4", "5"],
    userId: "123",
  },
  {
    id: 3,
    description: "Some descriptor text",
    img: "",
    name: "test3",
    netLikes: -5,
    thumbsDownVoters: ["1", "2", "3", "4", "5"],
    userId: "123",
  },
  {
    id: 4,
    description: "Some descriptor text",
    img: "",
    name: "test4",
    netLikes: -3,
    thumbsUpVoters: ["1", "2"],
    thumbsDownVoters: ["1", "2", "3", "4", "5"],
    userId: "123",
  },
  {
    id: 5,
    description: "Some descriptor text",
    img: "",
    name: "test5",
    netLikes: 4,
    thumbsUpVoters: ["1", "2", "3", "4", "5"],
    thumbsDownVoters: ["1"],
    userId: "123",
  },
  {
    id: 6,
    description: "Some descriptor text",
    img: "",
    name: "test6",
    netLikes: -1,
    thumbsUpVoters: ["1", "2", "3", "4"],
    thumbsDownVoters: ["1", "2", "3", "4", "5"],
    userId: "123",
  },
  {
    id: 7,
    description: "Some descriptor text",
    img: "",
    name: "test7",
    netLikes: 4,
    thumbsUpVoters: ["1", "2", "3", "4", "5"],
    thumbsDownVoters: ["1"],
    userId: "123",
  },
  {
    id: 8,
    description: "Some descriptor text",
    img: "",
    name: "test8",
    netLikes: -1,
    thumbsUpVoters: ["1", "2"],
    thumbsDownVoters: ["1", "2", "3"],
    userId: "123",
  },
  {
    id: 9,
    description: "Some descriptor text",
    img: "",
    name: "test9",
    netLikes: -1,
    thumbsDownVoters: ["1"],
    userId: "123",
  },
  {
    id: 10,
    description: "Some descriptor text",
    img: "",
    name: "test10",
    netLikes: -1,
    thumbsUpVoters: ["1", "2", "3", "4"],
    thumbsDownVoters: ["1", "2", "3", "4", "5"],
    userId: "123",
  },
  {
    id: 11,
    description: "Some descriptor text",
    img: "",
    name: "test11",
    netLikes: 16,
    thumbsUpVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
    ],
    userId: "123",
  },
  {
    id: 12,
    description: "Some descriptor text",
    img: "",
    name: "test12",
    netLikes: 16,
    thumbsUpVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
    ],
    thumbsDownVoteres: ["1", "2"],
    userId: "123",
  },
  {
    id: 13,
    description: "Some descriptor text",
    img: "",
    name: "test13",
    netLikes: 18,
    thumbsUpVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
    ],
    userId: "123",
  },
  {
    id: 14,
    description: "Some descriptor text",
    img: "",
    name: "test14",
    netLikes: 11,
    thumbsUpVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
    ],
    thumbsDownVoters: ["1", "2", "3", "4", "5"],
    userId: "123",
  },
  {
    id: 15,
    description: "Some descriptor text",
    img: "",
    name: "test15",
    netLikes: 8,
    thumbsUpVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    thumbsDownVoters: ["1"],
    userId: "123",
  },
  {
    id: 16,
    description: "Some descriptor text",
    img: "",
    name: "test16",
    netLikes: 7,
    thumbsUpVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    thumbsDownVoters: ["1", "2"],
    userId: "123",
  },
  {
    id: 17,
    description: "Some descriptor text",
    img: "",
    name: "test17",
    netLikes: 7,
    thumbsUpVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    thumbsDownVoters: ["1", "2"],
    userId: "123",
  },
  {
    id: 18,
    description: "Some descriptor text",
    img: "",
    name: "test18",
    netLikes: 9,
    thumbsUpVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    userId: "123",
  },
  {
    id: 19,
    description: "Some descriptor text",
    img: "",
    name: "test19te st19te st19tes t19test1 test19test1 9test19",
    netLikes: 8,
    thumbsUpVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    thumbsDownVoters: ["1"],
    userId: "123",
  },
  {
    id: 20,
    description: "Some descriptor text",
    img: "",
    name: "test20",
    netLikes: 9,
    thumbsUpVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    userId: "123",
  },
  {
    id: 21,
    description: "Some descriptor text",
    img: "",
    name: "test21",
    netLikes: -11,
    thumbsDownVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "10", "11"],
    userId: "123",
  },
  {
    id: 22,
    description: "Some descriptor text",
    img: "",
    name: "test22",
    netLikes: -6,
    thumbsUpVoters: ["1", "2", "3", "4", "5"],
    thumbsDownVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "10", "11"],
    userId: "123",
  },
  {
    id: 23,
    description: "Some descriptor text",
    img: "",
    name: "test23",
    netLikes: -7,
    thumbsDownVoters: ["1", "2", "3", "4", "5", "6", "7"],
    userId: "123",
  },
  {
    id: 24,
    description: "Some descriptor text",
    img: "",
    name: "test24",
    netLikes: -10,
    thumbsUpVoters: ["1"],
    thumbsDownVoters: ["1", "2", "3", "4", "5", "6", "7", "8"],
    userId: "123",
  },
  {
    id: 25,
    description: "Some descriptor text",
    img: "",
    name: "test25",
    netLikes: -9,
    thumbsUpVoters: ["1", "2"],
    thumbsDownVoters: ["1", "2", "3", "4", "5", "6", "7", "8", "10", "11"],
    userId: "123",
  },
  {
    id: 26,
    description: "Some descriptor text",
    img: "",
    name: "test26",
    netLikes: -20,
    thumbsDownVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    userId: "123",
  },
  {
    id: 27,
    description: "Some descriptor text",
    img: "",
    name: "test27",
    netLikes: -15,
    thumbsUpVoters: ["1", "2", "3", "4", "5"],
    thumbsDownVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    userId: "123",
  },
  {
    id: 28,
    description: "Some descriptor text",
    img: "",
    name: "test28",
    netLikes: -18,
    thumbsUpVoters: ["1", "2"],
    thumbsDownVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    userId: "123",
  },
  {
    id: 29,
    description: "Some descriptor text",
    img: "",
    name: "test29",
    netLikes: -16,
    thumbsUpVoters: ["1", "2", "3", "4"],
    thumbsDownVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    userId: "123",
  },
  {
    id: 30,
    description: "Some descriptor text",
    img: "",
    name: "test1",
    netLikes: -18,
    thumbsUpVoters: ["1", "2"],
    thumbsDownVoters: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
    ],
    userId: "123",
  },
  {
    id: 31,
    description: "Some descriptor text",
    img: "",
    name: "test1",
    userId: "123",
  },
  {
    id: 32,
    description: "Some descriptor text",
    img: "",
    name: "test1",
    userId: "123",
  },
  {
    id: 33,
    description: "Some descriptor text",
    img: "",
    name: "test1",
    netLikes: 0,
    userId: "123",
  },
];
